# Generated by Django 3.0 on 2020-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_vehiculo_odo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehiculos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='odo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometro'),
        ),
    ]
