# Generated by Django 3.0 on 2020-01-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_auto_20200117_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('foto', models.ImageField(upload_to='vehiculos', verbose_name='Foto')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehiculos', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehiculo.SubirImagen'),
        ),
    ]
