# Generated by Django 3.0 on 2020-01-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_auto_20200117_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto',
        ),
    ]
