# Generated by Django 3.0 on 2020-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_remove_vehiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(default='vehiculos/logo.png', upload_to='vehiculos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='Matrícula'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('placa',)},
        ),
    ]
