# Generated by Django 3.0 on 2020-01-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_user', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Avatar')),
                ('madrid', models.BooleanField(default=False, verbose_name='Madrid')),
                ('salamanca', models.BooleanField(default=False, verbose_name='Salamanca')),
                ('valladolid', models.BooleanField(default=False, verbose_name='Valladolid')),
                ('las_palmas', models.BooleanField(default=False, verbose_name='Las Palmas')),
                ('mallorca', models.BooleanField(default=False, verbose_name='Mallorca')),
                ('zamora', models.BooleanField(default=False, verbose_name='Zamora')),
                ('movil', models.TextField(blank=True, max_length=20, null=True, verbose_name='Télefono Movil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
