# Generated by Django 3.0 on 2020-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todas',
            field=models.BooleanField(default=False, verbose_name='Todas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Télefono Movil'),
        ),
    ]
