# Generated by Django 3.0 on 2020-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200122_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_user',
            field=models.BooleanField(default=False, verbose_name='Permisos Usuarios'),
        ),
        migrations.AddField(
            model_name='profile',
            name='superus',
            field=models.BooleanField(default=False, verbose_name='SuperUser'),
        ),
    ]
