# Generated by Django 3.0 on 2020-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200124_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_vehiculos',
            field=models.BooleanField(default=False, verbose_name='Crear Vehiculos'),
        ),
    ]
