# Generated by Django 3.0 on 2020-01-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200124_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
    ]
