# Generated by Django 3.0 on 2020-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.FloatField()),
                ('telefono_fijo', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
